

# This file was *autogenerated* from the file hecke_lucas_v3.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_65 = Integer(65); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_0p001 = RealNumber('0.001'); _sage_const_25 = Integer(25); _sage_const_0p5 = RealNumber('0.5'); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6); _sage_const_10 = Integer(10); _sage_const_15 = Integer(15); _sage_const_20 = Integer(20); _sage_const_30 = Integer(30); _sage_const_21 = Integer(21); _sage_const_35 = Integer(35); _sage_const_0p6 = RealNumber('0.6'); _sage_const_50 = Integer(50); _sage_const_31 = Integer(31); _sage_const_37 = Integer(37); _sage_const_41 = Integer(41); _sage_const_8 = Integer(8); _sage_const_43 = Integer(43); _sage_const_47 = Integer(47); _sage_const_9 = Integer(9); _sage_const_12 = Integer(12); _sage_const_18 = Integer(18); _sage_const_44 = Integer(44); _sage_const_68 = Integer(68); _sage_const_60 = Integer(60); _sage_const_26 = Integer(26); _sage_const_100 = Integer(100)# hecke_lucas_v3.sage
# Run: sage hecke_lucas_v3.sage
from sage.all import *

PHI = (_sage_const_1  + sqrt(_sage_const_5 ))/_sage_const_2 
LOG_PHI = float(log(PHI))

def lucas_float(k):
    return float(PHI**k + PHI**(-k))

print("=" * _sage_const_65 )
print("HECKE EIGENVALUE COMPUTATION v3")
print("Fixed API calls for Sage modular forms + Brandt modules")
print("=" * _sage_const_65 )
print()

# ── Step 1: Newforms at various levels ──────────────────────────────────────
print("STEP 1: NEWFORMS AND HECKE EIGENVALUES")
print()

def check_newforms(level, weight=_sage_const_2 ):
    try:
        S = CuspForms(Gamma0(level), weight)
        d = S.dimension()
        if d == _sage_const_0 :
            return
        print(f"Level {level}, weight {weight}: dim={d}")
        # Get newforms via decomposition
        try:
            D = S.new_subspace().decomposition()
            for i, piece in enumerate(D):
                print(f"  Newform {i+_sage_const_1 } (dim {piece.dimension()}):")
                # Hecke eigenvalues via characteristic polynomial
                for p in [_sage_const_2 , _sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 , _sage_const_17 , _sage_const_19 , _sage_const_23 , _sage_const_29 ]:
                    try:
                        T = piece.hecke_matrix(p)
                        cp = T.charpoly()
                        roots = cp.roots(ring=QQbar)
                        evals = [float(r[_sage_const_0 ].real()) for r in roots
                                 if abs(float(r[_sage_const_0 ].imag())) < _sage_const_1en6 ]
                        if evals:
                            for e in evals[:_sage_const_3 ]:
                                ratio = log(abs(e))/LOG_PHI if abs(e) > _sage_const_0p001  else _sage_const_0 
                                nearest_k = min(range(_sage_const_25 ),
                                    key=lambda k: abs(lucas_float(k)-abs(e)))
                                Lk = lucas_float(nearest_k)
                                match = "LUCAS!" if abs(abs(e)-Lk) < _sage_const_0p5  else ""
                                print(f"    p={p:2d}: a_p={e:.4f}  "
                                      f"log/logphi={float(ratio):.4f}  "
                                      f"nearest L_{nearest_k}={Lk:.3f} {match}")
                    except Exception as e2:
                        pass
        except Exception as e:
            print(f"  Decomposition error: {e}")
            # Try direct Hecke operators
            try:
                for p in [_sage_const_2 , _sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 , _sage_const_17 , _sage_const_19 , _sage_const_23 , _sage_const_29 ]:
                    T = S.hecke_operator(p).matrix()
                    evals = [float(e.real()) for e in T.eigenvalues()
                             if abs(float(e.imag())) < _sage_const_1en6 ]
                    if evals:
                        print(f"  p={p:2d}: eigenvalues = "
                              f"{[f'{e:.3f}' for e in evals[:_sage_const_4 ]]}")
            except:
                pass
    except Exception as e:
        print(f"Level {level}: {e}")

for level in [_sage_const_3 , _sage_const_5 , _sage_const_6 , _sage_const_10 , _sage_const_15 , _sage_const_20 , _sage_const_30 ]:
    check_newforms(level, _sage_const_2 )
    print()

# ── Step 2: Direct modular symbols approach ──────────────────────────────────
print("=" * _sage_const_65 )
print("STEP 2: MODULAR SYMBOLS (more robust)")
print("=" * _sage_const_65 )
print()

for level in [_sage_const_5 , _sage_const_6 , _sage_const_15 , _sage_const_20 ]:
    try:
        M = ModularSymbols(level, _sage_const_2 , sign=_sage_const_1 )
        S = M.cuspidal_subspace()
        if S.dimension() == _sage_const_0 :
            continue
        print(f"Level {level}: cuspidal dim = {S.dimension()}")
        for p in [_sage_const_2 , _sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 , _sage_const_17 , _sage_const_19 , _sage_const_23 , _sage_const_29 ]:
            if p.divides(level):
                continue
            try:
                T = S.hecke_matrix(p)
                cp = T.charpoly()
                # Try to get rational eigenvalues
                roots = cp.roots()  # rational roots
                if roots:
                    for r, mult in roots:
                        e = float(r)
                        ratio = log(abs(e))/LOG_PHI if abs(e) > _sage_const_0p001  else _sage_const_0 
                        nearest_k = min(range(_sage_const_25 ),
                            key=lambda k: abs(lucas_float(k)-abs(e)))
                        Lk = lucas_float(nearest_k)
                        match = "LUCAS!" if abs(abs(e)-Lk) < _sage_const_0p5  else ""
                        print(f"  p={p:2d}: a_p={e:.4f}  "
                              f"log/logphi={float(ratio):.4f}  "
                              f"L_{nearest_k}={Lk:.3f} {match}")
            except Exception as e2:
                pass
        print()
    except Exception as e:
        print(f"Level {level}: {e}")

# ── Step 3: Brandt module with correct syntax ────────────────────────────────
print("=" * _sage_const_65 )
print("STEP 3: BRANDT MODULES (correct API)")
print("=" * _sage_const_65 )
print()

# BrandtModule takes an integer (the discriminant of the quaternion algebra)
# For QQ: quaternion algebras ramified at a set of primes
# Discriminant = product of finite ramification primes

for disc in [_sage_const_6 , _sage_const_10 , _sage_const_15 , _sage_const_21 , _sage_const_35 ]:
    try:
        # Check if disc is a valid quaternion algebra discriminant
        # (product of an even number of primes... wait, over QQ
        # we need discriminant to be squarefree and have even number of
        # prime factors for definite algebras)
        B = BrandtModule(disc)
        print(f"BrandtModule({disc}): rank={B.dimension()}")
        for p in [_sage_const_2 , _sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 , _sage_const_17 , _sage_const_29 ]:
            try:
                T = B.hecke_matrix(p)
                evals = T.eigenvalues()
                evals_f = []
                for e in evals:
                    try:
                        evals_f.append(float(e))
                    except:
                        pass
                if evals_f:
                    lucas_hits = []
                    for e in evals_f:
                        for k in range(_sage_const_20 ):
                            if abs(abs(e) - lucas_float(k)) < _sage_const_0p6 :
                                lucas_hits.append(f"|{e:.2f}|≈L_{k}")
                    hit_str = " ".join(lucas_hits)
                    print(f"  T_{p:2d}: {[f'{e:.3f}' for e in evals_f[:5]]} "
                          f"{hit_str}")
            except Exception as e2:
                print(f"  T_{p}: {e2}")
        print()
        break
    except Exception as e:
        print(f"BrandtModule({disc}): {e}")

# ── Step 4: Direct check using known level-5 eta product ─────────────────────
print("=" * _sage_const_65 )
print("STEP 4: LEVEL 5 MODULAR FORM (direct q-expansion)")
print("=" * _sage_const_65 )
print()
print("The unique newform of level 5, weight 2 is:")
print("  f = q - 2q^2 - 2q^3 + 2q^4 + q^5 + 4q^6 - ...")
print("  This corresponds to the elliptic curve y^2+y = x^3-x^2-10x-10")
print("  (Cremona label 50a, or 5a after twist)")
print()

# Construct via q-expansion
try:
    R = PowerSeriesRing(QQ, default_prec=_sage_const_50 , names=('q',)); (q,) = R._first_ngens(1)
    # Level 5 newform coefficients (known)
    # a_p for the unique newform of level 5 weight 2:
    # p=2: -2, p=3: -2, p=5: (bad), p=7: 2, p=11: -2, p=13: 6, p=17: 2
    # p=19: -6, p=23: -2, p=29: 6
    known_ap = {_sage_const_2 :-_sage_const_2 , _sage_const_3 :-_sage_const_2 , _sage_const_5 :_sage_const_1 , _sage_const_7 :_sage_const_2 , _sage_const_11 :-_sage_const_2 , _sage_const_13 :_sage_const_6 , _sage_const_17 :_sage_const_2 ,
                _sage_const_19 :-_sage_const_6 , _sage_const_23 :-_sage_const_2 , _sage_const_29 :_sage_const_6 , _sage_const_31 :-_sage_const_6 , _sage_const_37 :-_sage_const_4 , _sage_const_41 :-_sage_const_8 , _sage_const_43 :-_sage_const_4 , _sage_const_47 :_sage_const_0 }
    
    print(f"Known Hecke eigenvalues for level-5 newform:")
    print(f"  {'p':>4}  {'a_p':>6}  {'|a_p|':>6}  "
          f"{'log|a_p|/logphi':>16}  {'nearest L_k':>14}  {'dist':>8}")
    print("  " + "-"*_sage_const_65 )
    
    for p, ap in sorted(known_ap.items()):
        if ap == _sage_const_0 :
            continue
        ratio = log(abs(ap))/LOG_PHI if abs(ap) > _sage_const_0p5  else _sage_const_0 
        nearest_k = min(range(_sage_const_20 ), key=lambda k: abs(lucas_float(k)-abs(ap)))
        Lk = lucas_float(nearest_k)
        dist = abs(abs(ap) - Lk)
        match = "LUCAS!" if dist < _sage_const_0p5  else ""
        print(f"  {p:>4}  {ap:>6}  {abs(ap):>6.3f}  "
              f"{float(ratio):>16.6f}  "
              f"L_{nearest_k}={Lk:.3f}  {dist:>8.4f} {match}")
except Exception as e:
    print(f"Error: {e}")

# ── Step 5: The key number check ─────────────────────────────────────────────
print()
print("=" * _sage_const_65 )
print("STEP 5: THE KEY NUMBER — a_7 AND THE MUON MASS")
print("=" * _sage_const_65 )
print()
print("From conjectured Hecke eigenvalue formula:")
print(f"  a_7 (conjectured) = sqrt(7) * L_9 = {_sage_const_7 **_sage_const_0p5 :.4f} * {lucas_float(_sage_const_9 ):.4f}")
conj_a7 = _sage_const_7 **_sage_const_0p5  * lucas_float(_sage_const_9 )
print(f"  a_7 = {conj_a7:.6f}")
print(f"  log(a_7)/log(phi) = {log(conj_a7)/LOG_PHI:.6f}")
print()
print(f"From level-5 newform (if applicable):")
print(f"  a_7 = 2 (known)")
print(f"  log(2)/log(phi) = {log(_sage_const_2 )/LOG_PHI:.6f}")
print()
print("Muon mass quantum number: q=44, q/4 = 11.000")
print(f"  conjectured a_7: log/logphi = {log(conj_a7)/LOG_PHI:.4f} "
      f"(vs muon q/4 = 11.000)")
print(f"  actual a_7 (level 5): log/logphi = {log(_sage_const_2 )/LOG_PHI:.4f}")
print()
print("CONCLUSION:")
print("  The level-5 form gives a_7=2, which does NOT match the conjecture.")
print("  The relevant automorphic form for M_PMNS is NOT the level-5 newform.")
print("  The correct form lives over Q(sqrt(-3)), not over Q.")
print()
print("NEXT: Need Hilbert modular forms or Bianchi modular forms over Q(sqrt(-3)).")
print("  sage: BianchiModularForms(QuadraticField(-3), level=...)")
print("  This is the correct automorphic object for M_PMNS.")

# ── Step 6: Norm equation approach ──────────────────────────────────────────
print()
print("=" * _sage_const_65 )
print("STEP 6: NORM EQUATION IN Q(sqrt(-3)) AT SMALL NORMS")
print("=" * _sage_const_65 )
print()
print("Elements of Z[omega] with norm = SM mass phi-lattice values:")
print()

K = QuadraticField(-_sage_const_3 , names=('w',)); (w,) = K._first_ngens(1)
OK = K.ring_of_integers()

# For each SM mass quantum number q, check if norm q/4 has solutions
# i.e., does there exist a+b*omega in Z[omega] with N(a+b*omega) = phi^(q/4)?
# More tractable: check norms that are close to phi^(q/4) values

target_norms = {
    'u': (_sage_const_12 , float(PHI**(_sage_const_12 /_sage_const_4 ))),   # q=12, phi^3 = 4.236
    'd': (_sage_const_18 , float(PHI**(_sage_const_18 /_sage_const_4 ))),   # q=18, phi^4.5 = 8.719
    's': (_sage_const_43 , float(PHI**(_sage_const_43 /_sage_const_4 ))),   # q=43
    'mu':(_sage_const_44 , float(PHI**(_sage_const_44 /_sage_const_4 ))),   # q=44, phi^11 = 199.005
    'tau':(_sage_const_68 ,float(PHI**(_sage_const_68 /_sage_const_4 ))),   # q=68, phi^17
}

print(f"  {'fermion':>7}  {'q':>5}  {'phi**(q/_sage_const_4 )':>12}  "
      f"{'nearest norm N':>15}  {'element':>15}")
print("  "+"-"*_sage_const_60 )

for name, (q, target) in target_norms.items():
    # Find Eisenstein integers with norm closest to target
    best_dist = float('inf')
    best_elem = None
    best_norm = None
    for a in range(-_sage_const_25 , _sage_const_26 ):
        for b in range(-_sage_const_25 , _sage_const_26 ):
            N = a**_sage_const_2  - a*b + b**_sage_const_2 
            if N <= _sage_const_0 : continue
            dist = abs(N - target)
            if dist < best_dist:
                best_dist = dist
                best_elem = (a, b)
                best_norm = N
    if best_elem:
        a, b = best_elem
        rel_err = best_dist/target*_sage_const_100 
        print(f"  {name:>7}  {q:>5}  {target:>12.3f}  "
              f"{best_norm:>15}  "
              f"({a},{b})  err={rel_err:.2f}%")

print()
print("If any norm equals phi^(q/4) exactly, that Eisenstein integer")
print("would be the algebraic witness for the fermion mass.")
print()
print("Note: phi^(q/4) is irrational for most q, so exact matches")
print("require irrational norms -- which don't exist in Z[omega].")
print("The question is whether the NEAREST integer norm is special.")

