

# This file was *autogenerated* from the file lll_witness_search.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1p0 = RealNumber('1.0'); _sage_const_206p77 = RealNumber('206.77'); _sage_const_3477p22 = RealNumber('3477.22'); _sage_const_4p24 = RealNumber('4.24'); _sage_const_9p14 = RealNumber('9.14'); _sage_const_182p78 = RealNumber('182.78'); _sage_const_2495p11 = RealNumber('2495.11'); _sage_const_8180p04 = RealNumber('8180.04'); _sage_const_338082p19 = RealNumber('338082.19'); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_3 = Integer(3); _sage_const_0p5 = RealNumber('0.5'); _sage_const_1 = Integer(1); _sage_const_17 = Integer(17); _sage_const_5 = Integer(5); _sage_const_10 = Integer(10); _sage_const_6 = Integer(6); _sage_const_4 = Integer(4); _sage_const_200 = Integer(200); _sage_const_50 = Integer(50); _sage_const_20 = Integer(20); _sage_const_250 = Integer(250); _sage_const_70 = Integer(70); _sage_const_65 = Integer(65); _sage_const_120 = Integer(120); _sage_const_8 = Integer(8); _sage_const_100 = Integer(100); _sage_const_150 = Integer(150); _sage_const_9 = Integer(9); _sage_const_13 = Integer(13); _sage_const_15 = Integer(15); _sage_const_16 = Integer(16); _sage_const_30 = Integer(30); _sage_const_2024 = Integer(2024); _sage_const_80 = Integer(80); _sage_const_0p02 = RealNumber('0.02')# lll_witness_search.sage
# Use LLL to find optimal norm witnesses for large mass ratios
# This replaces brute-force search for heavy fermions (t quark)
# The LLL is ONLY the search method — the statistical analysis
# uses the same null model framework as null_model_pipeline_v2.sage
# Run: sage lll_witness_search.sage

from sage.all import *
import numpy as np

MASSES = {
    "e":   _sage_const_1p0 ,
    "mu":  _sage_const_206p77 ,
    "tau": _sage_const_3477p22 ,
    "u":   _sage_const_4p24 ,
    "d":   _sage_const_9p14 ,
    "s":   _sage_const_182p78 ,
    "c":   _sage_const_2495p11 ,
    "b":   _sage_const_8180p04 ,
    "t":   _sage_const_338082p19 ,
}

def is_prime_py(n):
    n = int(n)
    if n < _sage_const_2 : return False
    if n == _sage_const_2 : return True
    if n % _sage_const_2  == _sage_const_0 : return False
    for i in range(_sage_const_3 , int(n**_sage_const_0p5 )+_sage_const_1 , _sage_const_2 ):
        if n%i==_sage_const_0 : return False
    return True

# ── Norm functions ────────────────────────────────────────────────────────────
def norm_eisenstein(a, b):
    a,b = int(a),int(b)
    n = a*a - a*b + b*b
    return n if n > _sage_const_0  else _sage_const_0 

def norm_sqrt17(a, b):
    a,b = int(a),int(b)
    return abs(a*a - _sage_const_17 *b*b)

def norm_sqrt5(a, b):
    a,b = int(a),int(b)
    return abs(a*a - _sage_const_5 *b*b)

# ── LLL-accelerated witness search ────────────────────────────────────────────
def lll_witness(m, norm_func, norm_matrix, scale=_sage_const_10 **_sage_const_6 ):
    """
    Use LLL to find best (a,b) with norm_func(a,b) ≈ m.

    The lattice: embed the problem as finding short vectors in
    a 3D lattice that balances closeness to m and lattice structure.

    norm_matrix = [[A, B], [B, C]] defines N(a,b) = Aa^2 + 2Bab + Cb^2
    """
    m = float(m)
    # Augmented lattice:
    # Row 0: [scale, 0, A]    -> a-direction
    # Row 1: [0, scale, C]    -> b-direction
    # Row 2: [scale*m, 0, 0]  -> target

    # Use CVP (closest vector problem) approximation via LLL
    # Build basis for the lattice of vectors (a, b, a*A+b*B, a*B+b*C)
    A = float(norm_matrix[_sage_const_0 ][_sage_const_0 ])
    B = float(norm_matrix[_sage_const_0 ][_sage_const_1 ])
    C = float(norm_matrix[_sage_const_1 ][_sage_const_1 ])

    # Simple 2D lattice with augmented target
    M = scale
    # Lattice basis in 3D: columns represent (a_coeff, b_coeff, norm_coeff)
    basis = Matrix(ZZ, [
        [M, _sage_const_0 , int(A*M)],
        [_sage_const_0 , M, int(C*M)],
        [_sage_const_0 , _sage_const_0 , _sage_const_1 ],
    ])

    # Target: we want norm ≈ m, so target vector is (0, 0, int(m*M))
    # CVP is NP-hard in general but LLL gives 2^n approximation
    # For our 2D case, we can just do bounded brute force + LLL hint

    # LLL-reduced basis
    L = basis.LLL()

    # Extract candidate solutions from reduced basis rows
    candidates = []
    for row in L:
        for sign_a in [_sage_const_1 , -_sage_const_1 ]:
            for sign_b in [_sage_const_1 , -_sage_const_1 ]:
                # Each LLL vector gives a lattice direction
                # Try multiples up to small radius
                for k1 in range(-_sage_const_3 , _sage_const_4 ):
                    for k2 in range(-_sage_const_3 , _sage_const_4 ):
                        vec = k1 * L[_sage_const_0 ] + k2 * L[_sage_const_1 ]
                        # Decode a, b from vector
                        # The first two components encode a,b scaled by M
                        if M > _sage_const_0 :
                            a_approx = vec[_sage_const_0 ] / M
                            b_approx = vec[_sage_const_1 ] / M
                            for da in [-_sage_const_1 ,_sage_const_0 ,_sage_const_1 ]:
                                for db in [-_sage_const_1 ,_sage_const_0 ,_sage_const_1 ]:
                                    a = int(round(a_approx)) + da
                                    b = int(round(b_approx)) + db
                                    n = int(norm_func(a, b))
                                    if n > _sage_const_0 :
                                        err = abs(n - m)/m
                                        candidates.append((err, n, a, b))

    # Also do small brute force for safety
    R = min(_sage_const_200 , max(_sage_const_50 , int(m**_sage_const_0p5  / _sage_const_10 ) + _sage_const_20 ))
    for a in range(-R, R+_sage_const_1 , max(_sage_const_1 , R//_sage_const_50 )):
        for b in range(-R, R+_sage_const_1 , max(_sage_const_1 , R//_sage_const_50 )):
            n = int(norm_func(a, b))
            if n > _sage_const_0 :
                err = abs(n - m)/m
                candidates.append((err, n, a, b))

    if not candidates:
        return _sage_const_0 , (_sage_const_0 ,_sage_const_0 ), _sage_const_1p0 

    candidates.sort()
    best_err, best_n, best_a, best_b = candidates[_sage_const_0 ]
    return best_n, (best_a, best_b), float(best_err)

# ── Norm matrices for LLL ─────────────────────────────────────────────────────
# Eisenstein: N(a,b) = a^2 - ab + b^2 = [[1,-1/2],[-1/2,1]] (pos def)
M_EISENSTEIN = [[_sage_const_1 , -_sage_const_1 ], [-_sage_const_1 , _sage_const_4 ]]  # scaled to integers: 4*(a^2-ab+b^2)

# Z[sqrt(17)]: N(a,b) = |a^2 - 17b^2|  (indefinite, use |.|)
# For LLL we use the positive part: a^2 + 17b^2 as proxy
M_SQRT17_POS = [[_sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_17 ]]

# Z[sqrt(5)]: similarly
M_SQRT5_POS  = [[_sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_5 ]]

# ── Direct brute force for verification (wider radius) ────────────────────────
def brute_witness(m, norm_func, R=_sage_const_250 ):
    """Extended brute force for verification."""
    m = float(m)
    best_err = _sage_const_1p0 
    best_n = _sage_const_0 ; best = (_sage_const_0 ,_sage_const_0 )
    for a in range(-R, R+_sage_const_1 ):
        for b in range(-R, R+_sage_const_1 ):
            n = int(norm_func(a, b))
            if n <= _sage_const_0 : continue
            err = abs(n - m)/m
            if err < best_err:
                best_err = err; best_n = n; best = (a,b)
    return best_n, best, float(best_err)

# ── Run analysis ──────────────────────────────────────────────────────────────
print("="*_sage_const_70 )
print("LLL-ACCELERATED FERMION MASS WITNESS SEARCH")
print("="*_sage_const_70 )
print()

PHI = float((_sage_const_1 +_sage_const_5 **_sage_const_0p5 )/_sage_const_2 )

print("LEPTON SECTOR: Z[omega] Eisenstein norms")
print(f"{'f':>5} {'m/m_e':>12}  {'N':>10}  {'witness':>14}  {'err%':>8}  {'notes'}")
print("-"*_sage_const_65 )

for name in ["mu", "tau"]:
    m = float(MASSES[name])
    N, (a,b), err = brute_witness(m, norm_eisenstein, R=_sage_const_120 )
    verify = norm_eisenstein(a,b)
    prime = is_prime_py(N) if _sage_const_0  < N < _sage_const_10 **_sage_const_8  else False
    mod3 = N%_sage_const_3  if N > _sage_const_0  else -_sage_const_1 
    print(f"{name:>5} {m:>12.4f}  {N:>10}  ({a:4},{b:4})    {err*_sage_const_100 :>8.4f}%  "
          f"prime={prime} mod3={mod3}")

print()
print("QUARK SECTOR: Z[sqrt(17)] norms")
print(f"{'f':>5} {'m/m_e':>12}  {'N':>10}  {'witness':>16}  {'err%':>8}  {'notes'}")
print("-"*_sage_const_70 )

for name in ["u","d","s","c","b","t"]:
    m = float(MASSES[name])
    # For t quark, need large radius
    R = _sage_const_250  if name == "t" else _sage_const_150 
    N, (a,b), err = brute_witness(m, norm_sqrt17, R=R)
    verify = norm_sqrt17(a,b)
    prime = is_prime_py(N) if _sage_const_0  < N < _sage_const_10 **_sage_const_8  else False
    mod17 = N%_sage_const_17  if N > _sage_const_0  else -_sage_const_1 
    splits = mod17 in [_sage_const_1 ,_sage_const_2 ,_sage_const_4 ,_sage_const_8 ,_sage_const_9 ,_sage_const_13 ,_sage_const_15 ,_sage_const_16 ] if N > _sage_const_0  else False
    print(f"{name:>5} {m:>12.4f}  {N:>10}  ({a:4},{b:5})    {err*_sage_const_100 :>8.4f}%  "
          f"prime={prime} mod17={mod17} split={splits}")

print()
print("COMPARISON: Z[sqrt(5)] norms (field of phi)")
print(f"{'f':>5} {'m/m_e':>12}  {'N':>10}  {'witness':>16}  {'err%':>8}")
print("-"*_sage_const_65 )

for name in ["mu","tau","u","d","s","c","b","t"]:
    m = float(MASSES[name])
    N, (a,b), err = brute_witness(m, norm_sqrt5, R=_sage_const_200 )
    print(f"{name:>5} {m:>12.4f}  {N:>10}  ({a:4},{b:5})    {err*_sage_const_100 :>8.4f}%")

print()
print("="*_sage_const_70 )
print("STATISTICAL COMPARISON: RANDOM DISCRIMINANTS vs STRUCTURED")
print("="*_sage_const_70 )
print()
print("Testing 20 random discriminants d (not 5,17) for comparison...")
print(f"{'d':>6}  {'mean_err%':>10}  {'f<_sage_const_2 %':>7}")
print("-"*_sage_const_30 )

import random
random.seed(_sage_const_2024 )
random_discs = [d for d in range(_sage_const_2 , _sage_const_100 )
                if d not in [_sage_const_5 ,_sage_const_17 ] and not any(d%p==_sage_const_0  and (d//p)%p==_sage_const_0 
                for p in range(_sage_const_2 ,int(d**_sage_const_0p5 )+_sage_const_1 ))][:_sage_const_20 ]

disc_results = []
for d in random_discs:
    def norm_d(a,b,dd=d): return abs(int(a)*int(a)-dd*int(b)*int(b))
    errs = []
    for name, m in MASSES.items():
        if name == 'e': continue
        N,(a,b),err = brute_witness(float(m), norm_d, R=_sage_const_80 )
        errs.append(err)
    mean_err = float(np.mean(errs))*_sage_const_100 
    f2 = sum(_sage_const_1  for e in errs if e < _sage_const_0p02 )/len(errs)
    disc_results.append((d, mean_err, f2))
    print(f"{d:>6}  {mean_err:>10.4f}%  {f2:>7.2f}")

random_mean_err = float(np.mean([r[_sage_const_1 ] for r in disc_results]))
random_f2 = float(np.mean([r[_sage_const_2 ] for r in disc_results]))

print(f"\nRandom d average: mean_err={random_mean_err:.4f}%  f<2%={random_f2:.2f}")
print()

# Structured results
struct_errs = {}
for model_name, norm_func in [
    ("Z[omega]",  norm_eisenstein),
    ("Z[sqrt17]", norm_sqrt17),
    ("Z[sqrt5]",  norm_sqrt5),
]:
    errs = []
    for name, m in MASSES.items():
        if name == 'e': continue
        R = _sage_const_250  if name == 't' else _sage_const_150 
        N,(a,b),err = brute_witness(float(m), norm_func, R=R)
        errs.append(err)
    mean_err = float(np.mean(errs))*_sage_const_100 
    f2 = sum(_sage_const_1  for e in errs if e < _sage_const_0p02 )/len(errs)
    struct_errs[model_name] = (mean_err, f2)
    p_val = sum(_sage_const_1  for r in disc_results if r[_sage_const_1 ] <= mean_err)/len(disc_results)
    print(f"{model_name:<12}: mean_err={mean_err:.4f}%  f<2%={f2:.2f}  "
          f"p<random: {p_val:.2f} ({sum(1 for r in disc_results if r[2]>=f2)}/{len(disc_results)} null models beat it in f<2%)")

print()
print("="*_sage_const_70 )
print("LATEX TABLE FOR PAPER")
print("="*_sage_const_70 )
print()
print(r"\begin{tabular}{llrrr}")
print(r"\toprule")
print(r"Fermion & Ring & $m_f/m_e$ & Norm $N$ & Error \\")
print(r"\midrule")

lepton_data = {}
for name in ["mu","tau"]:
    m = float(MASSES[name])
    N,(a,b),err = brute_witness(m, norm_eisenstein, R=_sage_const_120 )
    lepton_data[name] = (m, N, a, b, err)
    print(f"{name} & $\\mathbb{{Z}}[\\omega]$ & {m:.2f} & {N} & "
          f"${err*_sage_const_100 :.4f}\\%$ \\\\")

print(r"\midrule")
quark_data = {}
for name in ["u","d","s","c","b","t"]:
    m = float(MASSES[name])
    R = _sage_const_250  if name == "t" else _sage_const_150 
    N,(a,b),err = brute_witness(m, norm_sqrt17, R=R)
    quark_data[name] = (m, N, a, b, err)
    print(f"{name} & $\\mathbb{{Z}}[\\sqrt{{17}}]$ & {m:.2f} & {N} & "
          f"${err*_sage_const_100 :.4f}\\%$ \\\\")
print(r"\bottomrule")
print(r"\end{tabular}")

