

# This file was *autogenerated* from the file spectral_analysis_v2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4p5 = RealNumber('4.5'); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_50 = Integer(50); _sage_const_5 = Integer(5); _sage_const_51 = Integer(51); _sage_const_10 = Integer(10); _sage_const_100p0 = RealNumber('100.0'); _sage_const_2001 = Integer(2001); _sage_const_0p0 = RealNumber('0.0'); _sage_const_1en6 = RealNumber('1e-6'); _sage_const_0p25 = RealNumber('0.25'); _sage_const_0p5 = RealNumber('0.5'); _sage_const_1j = ComplexNumber(0, '1'); _sage_const_43 = Integer(43); _sage_const_4 = Integer(4); _sage_const_60 = Integer(60)#!/usr/bin/env sage
# spectral_analysis_v2.sage (overwrites previous version)

import snappy
import json
from sage.all import *

# ------------------------------------------------------------
# Convert Sage types to JSON serializable
# ------------------------------------------------------------
def to_json(obj):
    if isinstance(obj, (Integer, int)):
        return int(obj)
    if isinstance(obj, (float, RealNumber)):
        return float(obj)
    if isinstance(obj, complex):
        return {'real': obj.real, 'imag': obj.imag}
    if isinstance(obj, (list, tuple)):
        return [to_json(x) for x in obj]
    if isinstance(obj, dict):
        return {to_json(k): to_json(v) for k, v in obj.items()}
    return str(obj)

# ------------------------------------------------------------
# Geodesic lengths (distinct, up to cutoff)
# ------------------------------------------------------------
def get_lengths(M, cutoff=_sage_const_4p5 ):
    try:
        ls = M.length_spectrum(cutoff=cutoff)
        lens = []
        for g in ls:
            try:
                v = g.length
                if callable(v):
                    v = v()
                ell = float(complex(v).real)
                lens.append(ell)
            except:
                continue
        return sorted(set(lens))
    except Exception as e:
        print(f"  Error in length spectrum: {e}")
        return []

# ------------------------------------------------------------
# 1. Hecke operator spectrum
# ------------------------------------------------------------
def hecke_spectrum():
    res = {}
    # Brandt module discriminant 3
    try:
        B = QuaternionAlgebra(QQ, -_sage_const_1 , -_sage_const_3 )
        disc = B.discriminant()
        BM = BrandtModule(disc)
        dim = BM.dimension()
        res['brandt_disc3'] = {'dimension': int(dim)}
        if dim > _sage_const_0 :
            hecke = {}
            for p in primes(_sage_const_2 , _sage_const_50 ):
                if p % _sage_const_3  == _sage_const_1 :   # splits in Q(√-3)
                    Tp = BM.hecke_matrix(p)
                    if dim == _sage_const_1 :
                        hecke[int(p)] = int(Tp[_sage_const_0 ,_sage_const_0 ])
                    else:
                        hecke[int(p)] = [float(x) for x in Tp.eigenvalues()]
            res['brandt_disc3']['hecke'] = hecke
    except Exception as e:
        res['brandt_disc3'] = {'error': str(e)}
    # Newform level 5 weight 2
    try:
        forms = Newforms(_sage_const_5 , _sage_const_2 , names='a')
        if forms:
            f = forms[_sage_const_0 ]
            coeffs = f.qexp(_sage_const_51 )
            hecke = {}
            for p in primes(_sage_const_2 , _sage_const_50 ):
                if p != _sage_const_5 :
                    ap = coeffs[p]
                    if ap in ZZ:
                        hecke[int(p)] = int(ap)
                    else:
                        hecke[int(p)] = float(ap)
            res['newform_level5'] = {'dim': _sage_const_1 , 'hecke': hecke}
        else:
            res['newform_level5'] = {'error': 'No newforms'}
    except Exception as e:
        res['newform_level5'] = {'error': str(e)}
    return res

# ------------------------------------------------------------
# 2. Selberg zeros via sine sum (approximate)
# ------------------------------------------------------------
def selberg_zeros(lengths, max_zeros=_sage_const_10 ):
    from math import sinh, sin
    if not lengths:
        return []
    t_vals = [t/_sage_const_100p0  for t in range(_sage_const_2001 )]  # 0 to 20, step 0.01
    F = [_sage_const_0p0 ]*len(t_vals)
    for ell in lengths:
        if ell < _sage_const_1en6 :
            continue
        w = ell / (_sage_const_2  * sinh(ell/_sage_const_2 ))
        for i, t in enumerate(t_vals):
            F[i] += w * sin(t * ell)
    zeros = []
    for i in range(_sage_const_1 , len(F)):
        if F[i-_sage_const_1 ] * F[i] < _sage_const_0 :
            t0 = t_vals[i-_sage_const_1 ]
            t1 = t_vals[i]
            z = t0 + (t1 - t0) * (-F[i-_sage_const_1 ]) / (F[i] - F[i-_sage_const_1 ])
            zeros.append(z)
    zeros = sorted(set([round(z, _sage_const_5 ) for z in zeros if z > _sage_const_0 ]))
    return zeros[:max_zeros]

# ------------------------------------------------------------
# 3. Laplace eigenvalues from Selberg zeros (λ = 1/4 + r^2)
# ------------------------------------------------------------
def laplace_from_zeros(zeros):
    return [_sage_const_0p25  + r*r for r in zeros]

# ------------------------------------------------------------
# 4. Transfer operator resonances (s = 0.5 + i r)
# ------------------------------------------------------------
def transfer_resonances(zeros):
    return [_sage_const_0p5  + _sage_const_1j *z for z in zeros]

# ------------------------------------------------------------
# Main
# ------------------------------------------------------------
manifolds = [
    (_sage_const_1 , 'PMNS', snappy.OrientableClosedCensus[_sage_const_1 ]),
    (_sage_const_43 , 'CKM', snappy.OrientableClosedCensus[_sage_const_43 ])
]

results = {'hecke': hecke_spectrum()}

for idx, name, M in manifolds:
    print(f"\nProcessing {name} (idx {idx})...")
    vol = float(M.volume())
    lens = get_lengths(M, cutoff=_sage_const_4p5 )
    print(f"  Distinct geodesics ≤4.5: {len(lens)}")

    zeros = selberg_zeros(lens, max_zeros=_sage_const_10 )
    print(f"  Selberg zeros (r): {zeros[:_sage_const_5 ]}")
    laplace = laplace_from_zeros(zeros)
    print(f"  Laplace λ: {[round(l,_sage_const_4 ) for l in laplace[:_sage_const_5 ]]}")
    resonances = transfer_resonances(zeros)

    results[name] = {
        'index': idx,
        'volume': vol,
        'num_geodesics': len(lens),
        'selberg_zeros': zeros,
        'laplace_eigenvalues': laplace,
        'transfer_resonances': [{'real': s.real, 'imag': s.imag} for s in resonances]
    }

# Save JSON
outfile = 'spectral_results.json'
with open(outfile, 'w') as f:
    json.dump(to_json(results), f, indent=_sage_const_2 )
print(f"\nResults saved to {outfile}")

# Summary
print("\n" + "="*_sage_const_60 )
print("SUMMARY")
print("="*_sage_const_60 )
for name in ['PMNS', 'CKM']:
    if name in results:
        d = results[name]
        print(f"\n{name}:")
        print(f"  Volume: {d['volume']:.6f}")
        print(f"  Geodesics: {d['num_geodesics']}")
        print(f"  First 3 Selberg zeros: {d['selberg_zeros'][:_sage_const_3 ]}")
        print(f"  First 3 Laplace λ: {[round(l,_sage_const_4 ) for l in d['laplace_eigenvalues'][:_sage_const_3 ]]}")
        if d['transfer_resonances']:
            s0 = d['transfer_resonances'][_sage_const_0 ]
            print(f"  First resonance: s = {s0['real']} + {s0['imag']:.5f}i")
print("\nHecke spectrum is inside the JSON file.")

