

# This file was *autogenerated* from the file unified_fermion_witnesses.sage
from sage.all_cmdline import *   # import sage library

_sage_const_206p771 = RealNumber('206.771'); _sage_const_3477p22 = RealNumber('3477.22'); _sage_const_4p2361 = RealNumber('4.2361'); _sage_const_9p1368 = RealNumber('9.1368'); _sage_const_182p78 = RealNumber('182.78'); _sage_const_2495p11 = RealNumber('2495.11'); _sage_const_8180p04 = RealNumber('8180.04'); _sage_const_338082p19 = RealNumber('338082.19'); _sage_const_200 = Integer(200); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_17 = Integer(17); _sage_const_300 = Integer(300); _sage_const_100 = Integer(100); _sage_const_70 = Integer(70)#!/usr/bin/env sage
# unified_fermion_witnesses.sage
# Finds best approximations of m/m_e by norms in:
#   - Eisenstein integers Z[ω] for leptons (Q(√-3))
#   - Z[√17] for quarks (Q(√17))
# Outputs LaTeX table and verification.

from sage.all import *

# ------------------------------------------------------------
# Fermion mass ratios (PDG 2024) relative to electron
# ------------------------------------------------------------
ratios = {
    'mu'   : _sage_const_206p771 ,      # muon
    'tau'  : _sage_const_3477p22 ,      # tau
    'u'    : _sage_const_4p2361 ,       # up
    'd'    : _sage_const_9p1368 ,       # down  (approx, actual 9.14)
    's'    : _sage_const_182p78 ,       # strange
    'c'    : _sage_const_2495p11 ,      # charm
    'b'    : _sage_const_8180p04 ,      # bottom
    't'    : _sage_const_338082p19 ,    # top
}

# ------------------------------------------------------------
# Search in Eisenstein integers Z[ω], norm N = a² - a*b + b²
# ------------------------------------------------------------
def eisenstein_witness(target, bound=_sage_const_200 ):
    best_a, best_b = _sage_const_0 , _sage_const_0 
    best_norm = _sage_const_0 
    best_err = float('inf')
    for a in range(-bound, bound+_sage_const_1 ):
        for b in range(-bound, bound+_sage_const_1 ):
            norm = a*a - a*b + b*b
            if norm == _sage_const_0 : continue
            err = abs(norm - target) / target
            if err < best_err:
                best_err = err
                best_norm = norm
                best_a, best_b = a, b
    return best_a, best_b, best_norm, best_err

# ------------------------------------------------------------
# Search in Z[√17], norm N = |a² - 17*b²|
# ------------------------------------------------------------
def sqrt17_witness(target, bound=_sage_const_200 ):
    best_a, best_b = _sage_const_0 , _sage_const_0 
    best_norm = _sage_const_0 
    best_err = float('inf')
    for a in range(-bound, bound+_sage_const_1 ):
        for b in range(-bound, bound+_sage_const_1 ):
            norm = abs(a*a - _sage_const_17 *b*b)
            if norm == _sage_const_0 : continue
            err = abs(norm - target) / target
            if err < best_err:
                best_err = err
                best_norm = norm
                best_a, best_b = a, b
    return best_a, best_b, best_norm, best_err

# ------------------------------------------------------------
# LaTeX table generation
# ------------------------------------------------------------
def latex_table():
    lines = []
    lines.append("\\begin{tabular}{lcccccc}")
    lines.append("\\toprule")
    lines.append("Particle & $m/m_e$ & Field & Norm $N$ & Witness $(a,b)$ & Error \\\\")
    lines.append("\\midrule")
    
    # Leptons (Eisenstein)
    for p in ['mu', 'tau']:
        target = ratios[p]
        a,b,norm,err = eisenstein_witness(target, bound=_sage_const_300 )
        lines.append(f"{p} & {target:.2f} & $\\mathbb{{Z}}[\\omega]$ & ${norm}$ & $({a},{b})$ & ${err*_sage_const_100 :.3f}\\%$ \\\\")
    
    # Quarks (Z[√17])
    for p in ['u','d','s','c','b','t']:
        target = ratios[p]
        a,b,norm,err = sqrt17_witness(target, bound=_sage_const_300 )
        lines.append(f"{p} & {target:.2f} & $\\mathbb{{Z}}[\\sqrt{{17}}]$ & ${norm}$ & $({a},{b})$ & ${err*_sage_const_100 :.3f}\\%$ \\\\")
    
    lines.append("\\bottomrule")
    lines.append("\\end{tabular}")
    return "\n".join(lines)

# ------------------------------------------------------------
# Main
# ------------------------------------------------------------
print("="*_sage_const_70 )
print("UNIFIED ARITHMETIC WITNESSES FOR FERMION MASS RATIOS")
print("="*_sage_const_70 )
print()
print("Leptons (Eisenstein integers Z[ω], norm a²-ab+b²):")
for p in ['mu','tau']:
    a,b,norm,err = eisenstein_witness(ratios[p], bound=_sage_const_300 )
    print(f"  {p:3s}: target={ratios[p]:8.2f} → N({a:3d},{b:3d}) = {norm:5d}  error={err*_sage_const_100 :.4f}%")

print("\nQuarks (Z[√17], norm |a²-17b²|):")
for p in ['u','d','s','c','b','t']:
    a,b,norm,err = sqrt17_witness(ratios[p], bound=_sage_const_300 )
    print(f"  {p:3s}: target={ratios[p]:8.2f} → N({a:3d},{b:3d}) = {norm:6d}  error={err*_sage_const_100 :.4f}%")

print("\n" + "="*_sage_const_70 )
print("LaTeX table:")
print("="*_sage_const_70 )
print(latex_table())

