path = r"C:\dev\framework\papers\hyperbolic-flavor-torsion\gentry-hyperbolic-flavor-torsion.tex"
with open(path, encoding="utf-8") as f:
    tex = f.read()

# Add Margulis subsection after Proposition/Remark block, before Conjecture
old_conj = r"\begin{conjecture}"

margulis_section = (
    r"\subsection{Margulis asymptotics and the exponential decay law}"
    "\n\n"
    r"Proposition~\ref{prop:floors_zero} guarantees $\phi_{\rm floor}^{(k)}(L)\to 0$"
    "\n"
    r"but does not predict the rate.  Here we explain why exponential decay"
    "\n"
    r"is the natural expectation from the prime geodesic theorem."
    "\n\n"
    r"The prime geodesic theorem (Margulis~\cite{Margulis69}) gives"
    "\n"
    r"\begin{equation}"
    "\n"
    r"  \pi_\Gamma(T) \sim \frac{e^{2T}}{2T}, \qquad T\to\infty,"
    "\n"
    r"  \label{eq:pgt}"
    "\n"
    r"\end{equation}"
    "\n"
    r"for the count of primitive closed geodesics of length $\leq T$."
    "\n"
    r"The Ambient PGT~\cite{BalogBiggs23} and the equidistribution of homology"
    "\n"
    r"classes~\cite{Sunada85} together give, for each class $k\in\mathbb{Z}/5$"
    "\n"
    r"and each arc $J_\epsilon = \{\theta : |\phi_{\rm fold}|<\epsilon\}$"
    "\n"
    r"of measure $|J_\epsilon|=4\epsilon$,"
    "\n"
    r"\begin{equation}"
    "\n"
    r"  N^{(k)}(T,\epsilon)"
    "\n"
    r"  \;:=\;\#\{\gamma\in C_k : \ell(\gamma)\leq T,\;\phi_{\rm fold}(\gamma)<\epsilon\}"
    "\n"
    r"  \;\sim\; \frac{4\epsilon}{\pi}\cdot\frac{1}{5}\cdot\frac{e^{2T}}{2T}."
    "\n"
    r"  \label{eq:count}"
    "\n"
    r"\end{equation}"
    "\n"
    r"The spectral floor $\phi_{\rm floor}^{(k)}(L)$ is the value of $\epsilon$"
    "\n"
    r"at which $N^{(k)}(T_L,\epsilon)$ first reaches~1,"
    "\n"
    r"where $T_L$ is the maximum geodesic length achievable at word length $L$."
    "\n"
    r"Since $T_L \sim \alpha L$ for some constant $\alpha>0$ determined by the"
    "\n"
    r"generator lengths, equation~\eqref{eq:count} gives"
    "\n"
    r"\begin{equation}"
    "\n"
    r"  \phi_{\rm floor}^{(k)}(L)"
    "\n"
    r"  \;\sim\; C_k \cdot e^{-2\alpha L},"
    "\n"
    r"  \label{eq:floor_asymptotic}"
    "\n"
    r"\end{equation}"
    "\n"
    r"where the prefactor $C_k$ encodes the leading-order correction to the"
    "\n"
    r"equidistribution of twist angles within class~$k$."
    "\n"
    r"The Margulis asymptotics predict that the \emph{leading rate} $2\alpha$"
    "\n"
    r"is the same for all classes, but the \emph{prefactor} $C_k$ can differ."
    "\n"
    r"The class-dependent rates $c_k$ observed in our data (Table~\ref{tab:rates})"
    "\n"
    r"are therefore corrections to the leading term --- they reflect"
    "\n"
    r"class-to-class variation in the density of near-zero-twist geodesics"
    "\n"
    r"beyond what equidistribution predicts."
    "\n\n"
    r"The pairing $c_1=c_4$, $c_2=c_3$ (Table~\ref{tab:rates},"
    "\n"
    r"Figures~\ref{fig:decay}) is then a statement about the symmetry of"
    "\n"
    r"these corrections under the involution $k\mapsto -k$ (mod~5)."
    "\n"
    r"We conjecture that this symmetry is arithmetic in origin."
    "\n\n"
    + r"\begin{conjecture}"
)

tex = tex.replace(r"\begin{conjecture}", margulis_section, 1)

with open(path, "w", encoding="utf-8") as f:
    f.write(tex)
print("Margulis section added.")
