

# This file was *autogenerated* from the file hecke_lucas_v2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_21 = Integer(21); _sage_const_65 = Integer(65); _sage_const_12 = Integer(12); _sage_const_18 = Integer(18); _sage_const_43 = Integer(43); _sage_const_44 = Integer(44); _sage_const_68 = Integer(68); _sage_const_75 = Integer(75); _sage_const_106 = Integer(106); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_15 = Integer(15); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_13 = Integer(13); _sage_const_17 = Integer(17); _sage_const_19 = Integer(19); _sage_const_23 = Integer(23); _sage_const_29 = Integer(29); _sage_const_0p001 = RealNumber('0.001'); _sage_const_0 = Integer(0); _sage_const_20 = Integer(20); _sage_const_0p5 = RealNumber('0.5'); _sage_const_35 = Integer(35); _sage_const_10 = Integer(10); _sage_const_9 = Integer(9); _sage_const_45 = Integer(45)# hecke_lucas_v2.sage
# Run: sage hecke_lucas_v2.sage
from sage.all import *

PHI = (_sage_const_1  + sqrt(_sage_const_5 ))/_sage_const_2 
LOG_PHI = float(log(PHI))

def lucas_float(k):
    return float(PHI**k + PHI**(-k))

L = {}
for k in range(_sage_const_21 ):
    try:
        L[k] = ZZ(expand(PHI**k + PHI**(-k)))
    except:
        L[k] = lucas_float(k)

print("=" * _sage_const_65 )
print("Lucas numbers L_k = phi^k + phi^{-k}")
print("=" * _sage_const_65 )
for k in range(_sage_const_12 ):
    print(f"  L_{k:2d} = {L[k]}")
print()

print("Quarter-Lucas mass lattice positions:")
for q in [_sage_const_12 , _sage_const_18 , _sage_const_43 , _sage_const_44 , _sage_const_65 , _sage_const_68 , _sage_const_75 , _sage_const_106 ]:
    ell = q/_sage_const_4  * LOG_PHI
    print(f"  q={q:4d}: ell={ell:.5f}  phi^(q/4)={float(PHI**(q/_sage_const_4 )):.4f}")
print()

print("=" * _sage_const_65 )
print("HECKE EIGENVALUES OF MODULAR FORMS")
print("=" * _sage_const_65 )
print()

for level, weight in [(_sage_const_3 ,_sage_const_2 ),(_sage_const_3 ,_sage_const_4 ),(_sage_const_5 ,_sage_const_2 ),(_sage_const_6 ,_sage_const_2 ),(_sage_const_15 ,_sage_const_2 )]:
    try:
        S = Newforms(level, weight=weight, names='a')
        if not S:
            continue
        print(f"Level {level}, weight {weight}: {len(S)} newform(s)")
        for f in S[:_sage_const_2 ]:
            print(f"  Form: {f.label()}")
            print(f"  {'p':>4}  {'a_p':>10}  {'|a_p|':>8}  "
                  f"{'log|a_p|/logphi':>16}  {'nearest L_k':>14}")
            for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ,_sage_const_17 ,_sage_const_19 ,_sage_const_23 ,_sage_const_29 ]:
                try:
                    ap = f.hecke_eigenvalue(p)
                    ap_f = float(ap)
                    ratio = log(abs(ap_f))/LOG_PHI if abs(ap_f) > _sage_const_0p001  else _sage_const_0 
                    nearest_k = min(range(_sage_const_20 ),
                                   key=lambda k: abs(lucas_float(k)-abs(ap_f)))
                    nearest_L = lucas_float(nearest_k)
                    dist = abs(abs(ap_f) - nearest_L)
                    match = "LUCAS!" if dist < _sage_const_0p5  else ""
                    print(f"  {p:>4}  {ap_f:>10.4f}  {abs(ap_f):>8.4f}  "
                          f"{float(ratio):>16.6f}  "
                          f"L_{nearest_k}={nearest_L:.3f} {match}")
                except Exception as e:
                    print(f"  {p:>4}  error: {e}")
        print()
    except Exception as e:
        print(f"Level {level}, weight {weight}: {e}")
        print()

print("=" * _sage_const_65 )
print("LEVEL 5 NEWFORM (H1=Z/5 connection)")
print("=" * _sage_const_65 )
print()
try:
    S5 = Newforms(_sage_const_5 , weight=_sage_const_2 , names='a')
    if S5:
        f5 = S5[_sage_const_0 ]
        print(f"Newform: {f5.label()}")
        print(f"q-expansion: {f5.q_expansion(_sage_const_15 )}")
        print()
        print(f"{'p':>4}  {'a_p':>8}  {'L_k match?':>12}")
        print("-"*_sage_const_35 )
        for p in [_sage_const_2 ,_sage_const_3 ,_sage_const_5 ,_sage_const_7 ,_sage_const_11 ,_sage_const_13 ,_sage_const_17 ,_sage_const_19 ,_sage_const_23 ,_sage_const_29 ]:
            try:
                ap = ZZ(f5.hecke_eigenvalue(p))
                matches = [(k, L[k]) for k in range(_sage_const_15 )
                           if abs(ap - L[k]) <= _sage_const_1 ]
                mstr = f"≈ L_{matches[_sage_const_0 ][_sage_const_0 ]}={matches[_sage_const_0 ][_sage_const_1 ]}" if matches else ""
                print(f"{p:>4}  {ap:>8}  {mstr}")
            except Exception as e:
                print(f"{p:>4}  error: {e}")
except Exception as e:
    print(f"Error: {e}")

print()
print("=" * _sage_const_65 )
print("BRANDT MODULE (Quaternion algebra)")
print("=" * _sage_const_65 )
print()

for disc in [_sage_const_2 , _sage_const_3 , _sage_const_6 , _sage_const_10 , _sage_const_15 ]:
    try:
        A = QuaternionAlgebra(disc)
        O = A.maximal_order()
        B = BrandtModule(A, _sage_const_1 )
        print(f"Discriminant {disc}: rank={B.rank()}, "
              f"ramified at {A.ramified_primes()}")
        for p in [_sage_const_2 , _sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , _sage_const_13 , _sage_const_29 ]:
            try:
                T = B.hecke_matrix(p)
                evals = [float(e) for e in T.eigenvalues()]
                lucas_hits = []
                for e in evals:
                    for k in range(_sage_const_15 ):
                        if abs(abs(e) - lucas_float(k)) < _sage_const_0p5 :
                            lucas_hits.append(f"|{e:.3f}|≈L_{k}")
                hit_str = ", ".join(lucas_hits) if lucas_hits else ""
                print(f"  T_{p:2d} evals: {[f'{e:.3f}' for e in evals[:4]]}  "
                      f"{hit_str}")
            except Exception as e2:
                print(f"  T_{p}: {e2}")
        print()
        break  # use first working discriminant
    except Exception as e:
        print(f"Discriminant {disc}: {e}")

print()
print("=" * _sage_const_65 )
print("CONJECTURE SUMMARY")
print("=" * _sage_const_65 )
print()
print("Hecke-mass conjecture: a_p = L_{k(p)} * sqrt(N(p))")
print("where k(p) = degree at which p first appears in covering tower")
print()
covering = {_sage_const_2 :_sage_const_9 , _sage_const_3 :_sage_const_9 , _sage_const_7 :_sage_const_9 , _sage_const_11 :_sage_const_2 , _sage_const_29 :_sage_const_5 }
print(f"{'p':>4}  {'k':>4}  {'L_k':>8}  {'sqrt(N(p))':>12}  {'pred a_p':>10}")
print("-"*_sage_const_45 )
for p, deg in covering.items():
    Lk = lucas_float(deg)
    Np = p if (p == _sage_const_3  or p % _sage_const_3  == _sage_const_1 ) else p**_sage_const_2 
    pred = Lk * Np**_sage_const_0p5 
    print(f"{p:>4}  {deg:>4}  {Lk:>8.4f}  {Np**_sage_const_0p5 :>12.4f}  {pred:>10.4f}")
print()
print("Compare predicted a_p values with Brandt/newform eigenvalues above.")

